version: "3"
services:
  db:
    image: postgres
    container_name: postgresDb
    restart: always

    volumes:
      - psql:/var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=atlas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always

    volumes:
      - pgad:/var/lib/pgadmin

    ports:
      - "5050:80"

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
volumes:
  psql:
  pgad:
